server:
  port: 8093

# To See H2 Console in Browser:
# http://localhost:8092/h2-console
# Enabling H2 Console
spring:
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:claimsDB;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driverClassName: org.h2.Driver
    platform: h2
    username: sa
    password:
    hikari:
      # ===Número máximo de conexiones en el Pool
      maximum-pool-size: 10
      # ===Tiempo de espera de conexión de la base de datos
      connection-timeout: 30000
      # ====Número mínimo de conexiones inactivas
      minimum-idle: 5
      # ====Tiempo máximo para vivir una conexión inactiva
      idle-timeout: 180000
      # ====Este atributo controla el ciclo de vida máximo de la conexión en el grupo.
      max-lifetime: 90000
  # ===============================
  # JPA / HIBERNATE
  # ===============================
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.H2Dialect
    properties:
      hibernate:
        show_sql: true
        use_sql_comments: false
        format_sql: false
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8099/eureka/